# Generated by Django 2.1.4 on 2019-05-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempTable',
            fields=[
                ('FileID', models.AutoField(primary_key=True, serialize=False)),
                ('RootPath', models.CharField(max_length=1000)),
                ('FileName', models.CharField(max_length=250)),
                ('lineNumber', models.CharField(max_length=50)),
            ],
        ),
    ]
