# Generated by Django 2.2.1 on 2019-06-11 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cmp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temptable',
            name='RootPath',
        ),
        migrations.DeleteModel(
            name='FileTable',
        ),
        migrations.DeleteModel(
            name='PathTable',
        ),
        migrations.DeleteModel(
            name='TempTable',
        ),
    ]
