# Generated by Django 2.1.4 on 2019-05-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cmp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temptable',
            name='SearchTerm',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
    ]
