# Generated by Django 2.1.4 on 2019-05-20 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cmp', '0002_auto_20190515_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTable',
            fields=[
                ('FileID', models.AutoField(primary_key=True, serialize=False)),
                ('FileName', models.CharField(max_length=250)),
                ('Extension', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PathTable',
            fields=[
                ('PathID', models.AutoField(primary_key=True, serialize=False)),
                ('Path', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='filetable',
            name='RootPath',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_cmp.PathTable'),
        ),
    ]
