# Generated by Django 2.2.1 on 2019-06-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temptable',
            name='RootPath',
            field=models.CharField(max_length=1000),
        ),
    ]
