# Generated by Django 2.1.4 on 2018-12-29 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileName', models.CharField(max_length=250)),
                ('Extension', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PathTable',
            fields=[
                ('PathID', models.AutoField(primary_key=True, serialize=False)),
                ('Path', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='filetable',
            name='RootPath',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='searchFiles.PathTable'),
        ),
    ]
