# Generated by Django 2.1.4 on 2019-01-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchFiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filetable',
            name='id',
        ),
        migrations.AddField(
            model_name='filetable',
            name='FileID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
